name: Marskey
description: Marskey's Life
meta_description: "Never Stop Having Fun"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 
domain_name: "http://marskey.me"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate, jekyll-feed]

# Details for the RSS feed generator
url: ""
author: "lingfengMarskey"
author-pic: face.jpg
email: lingfengmarskey@gmail.com # your email

# Disqus config
disqus-shortname: "marskey"
